apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: mysql:5.7
        imagePullPolicy: Never
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "ktor"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "mypass"
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"