apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    storage: mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/db
    server: 192.168.1.50