apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    storage: nfs-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/prometheus
    server: 192.168.1.50