apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    storage: nfs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/grafana
    server: 192.168.1.50