apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30100
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort