apiViersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      tier: app
    strategy:
      type: RollingUpdate
      rollingUpdate:
	maxSurge: 3
        maxUnavailable: 3
    template:
      metadata:
        name: nginx
        labels:
          app: nginx
          tier: app
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80
